version: '3.8'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_DB: ${name}
    container_name: oerlikon_inventory_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      # Cambiamos a 3005:3005 porque tu main.ts usa el 3005
      - '3005:3005' 
    environment:
      - DATABASE_URL=postgresql://postgres:${pass}@db:5432/${name}
      # Estas variables deben coincidir con tu .env del backend
      - host=db
      - allowedOrigin=http://localhost:3000
    depends_on:
      - db
    container_name: oerlikon_inventory_backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      # Apuntamos al puerto correcto del backend
      - NEXT_PUBLIC_API_URL=http://localhost:3005
    depends_on:
      - backend
    container_name: oerlikon_inventory_frontend